Compile time option to run L0 Sampling code and better GraphZeppelin configuration
GraphStreamingProject/GraphZeppelin pull request #134
Opened 2023-07-26 05:44 UTC by etwest

The current code runs a support finding algorithm that is sufficient for CC but maybe not for other relevant graph algorithms. This pull request adds a compile time option to run the code that is provably an L0 sampling algorithm.

Additionally, it reflects changes made to the Guttering System configuration to allow for easy specification of the batch size as a function of the Supernode size. This is especially relevant when used in combination with a modified number of sketches.

2023-07-26 05:45 UTC, etwest commented
Note, merge pull request in GutterTree repo first and switch branch tag back to main before merging.

2023-10-04 16:49 UTC, DanielDeLayo requested changes

2023-10-04 16:49 UTC, DanielDeLayo commented on include/supernode.h
direct number of cols instead

2023-10-04 16:49 UTC, DanielDeLayo commented on src/l0_sampling/sketch.cpp
> +#else // Use support finding algorithm instead. Faster but no guarantee of uniform sample.
support finding algorithm?

2023-10-04 16:49 UTC, DanielDeLayo commented on src/l0_sampling/sketch.cpp
> +#else // Use support finding algorithm instead. Faster but no guarantee of uniform sample.
support finding algorithm?

2023-10-04 17:02 UTC, DanielDeLayo approved these changes

2023-10-04 17:08 UTC, merged