Refactor Graph class -> GraphSketchDriver + CCSketchAlg
GraphStreamingProject/GraphZeppelin pull request #135
Opened 2023-10-18 20:27 UTC by etwest

Still in progress

2023-10-19 19:37 UTC, DanielDeLayo commented on include/sketch.h
> +  size_t num_guesses;      // number of buckets per column
rename to buckets_per_column or something

2023-10-19 19:38 UTC, DanielDeLayo commented on include/graph_configuration.h
> +  friend class CCSketchAlg;
TODO: This should be separated into 2 configs?

2023-10-19 19:46 UTC, DanielDeLayo commented on include/sketch.h
> +  inline const char* get_bucket_memory_buffer() const { return (char*)buckets; }
get_readonly_buckets())

2023-10-19 20:59 UTC, DanielDeLayo requested changes

2023-10-19 20:59 UTC, DanielDeLayo commented on include/sketch.h
> +  static size_t guess_gen(size_t n) { return 2 * log2(n) - 2; }
calc_buckets_per_col()

2023-10-19 20:59 UTC, DanielDeLayo commented on include/sketch.h
> +  static size_t samples_gen(size_t n) { return ceil(log2(n) / num_samples_div); }
calc_max_samples()?

2023-10-19 20:59 UTC, DanielDeLayo commented on include/worker_thread_group.h
> +    // unpause the WorkerThreads
gts->set_non_block(false);

2023-10-19 20:59 UTC, DanielDeLayo commented on src/cc_sketch_alg.cpp
> +CCSketchAlg::CCSketchAlg(std::string input_file, GraphConfiguration config)
const reference input_file

2023-10-19 20:59 UTC, DanielDeLayo commented on src/cc_sketch_alg.cpp
> -  Supernode::configure(num_nodes, sketch_num_columns, sketches_factor);
Whiteboard graph serialization

2023-10-19 20:59 UTC, DanielDeLayo commented on src/cc_sketch_alg.cpp
> +    sketches[i] = new Sketch(num_nodes, seed, binary_in, FULL);
get rid of FULL

2023-10-19 20:59 UTC, DanielDeLayo commented on src/cc_sketch_alg.cpp
> +  unlikely_if(dsu_valid) {
maybe add a comment about cache coherency here?

2023-10-19 20:59 UTC, DanielDeLayo commented on src/sketch.cpp
> +  binary_in.read((char *)buckets, num_buckets * sizeof(Bucket));
consider using sketch size method here and below

2023-10-19 20:59 UTC, DanielDeLayo commented on src/sketch.cpp
> +  }
call reset samples?

2023-10-19 20:59 UTC, DanielDeLayo commented on src/sketch.cpp
> +  // TODO!
TODO!

2023-10-19 20:59 UTC, DanielDeLayo commented on src/sketch.cpp
> +  }
consider deletion or unlikely_if

2023-10-19 20:59 UTC, DanielDeLayo commented on src/sketch.cpp
> +  // TODO!
TODO!1!

2023-10-19 20:59 UTC, DanielDeLayo commented on src/sketch.cpp
> +  binary_out.write((char*) buckets, num_buckets * sizeof(Bucket));
use size function

2023-10-19 20:59 UTC, DanielDeLayo commented on src/sketch.cpp
> +  }
delete debug output
consider assert?

2023-10-19 20:59 UTC, DanielDeLayo commented on test/graph_test.cpp
> +    driver.worker_threads->flush_workers();
call prep_query instead

2023-10-20 17:28 UTC, DanielDeLayo commented
We need to change the sketch interface. Let us input the vector length, instead of the square root of the vector length.

2023-10-20 20:07 UTC, etwest commented on test/graph_test.cpp
> +    driver.worker_threads->flush_workers();
prep_query() doesn't do what we want because of the dsu optimization. So we need to do it manually.

2023-10-23 15:54 UTC, DanielDeLayo submitted a review, later dismissed
The .yml file is much more readable now!

2023-11-08 20:02 UTC, DanielDeLayo requested changes

2023-11-08 20:02 UTC, DanielDeLayo commented on include/cc_alg_configuration.h
> +  CCAlgConfiguration& operator=(const CCAlgConfiguration &) = delete;
Why are we against move and copy assignment operators? Is it the ambiguity?

(My reading of the spec tells me disabling copy-assign also disabled move-assign)

2023-11-08 20:02 UTC, DanielDeLayo commented on include/cc_sketch_alg.h
> +#include <atomic>  // REMOVE LATER
// REMOVE LATER

2023-11-08 20:02 UTC, DanielDeLayo commented on src/cc_sketch_alg.cpp
> +             .count();
We should require the seed be given as input. While microseconds might be enough when using multiple CCSketchAlgs to avoid most duplicate seeds, I'd rather give the user control of the randomness generation.

2023-11-08 20:02 UTC, DanielDeLayo commented on src/sketch.cpp
> +  buckets = new Bucket[num_buckets];
I'm tempted to move the deterministic bucket to Sketch, so you can access it without a pointer lookup.
The main downside of this is getting a list of buckets would be more difficult.

2023-11-08 20:02 UTC, DanielDeLayo commented on tools/benchmark/graphcc_bench.cpp
> +        GraphStreamUpdate &upd = upds[i];
DoNotOptimise removed-- making sure this is intentional

2023-11-08 20:02 UTC, DanielDeLayo commented on tools/test_correctness.cpp
> +    size_t edge_seed = gen();
there's no parallelism here-- can we not use gen for all of our randomness? Why do we reseed with a random number every iteration?

Randomly generating seeds (as well as sequential seeds) are both a bit messy. (birthday paradox and risk of correlation)

I don't think it matters here too much, but every now and then I enter into the raddit hole of using RNG to seed RNG and exit without a clear indication of what's best. This post claims to know more than I do.

https://stats.stackexchange.com/questions/233061/best-way-to-seed-n-independent-random-number-generators-from-1-value

2023-11-09 20:50 UTC, etwest commented on src/cc_sketch_alg.cpp
> +             .count();
Agreed!

2023-11-09 20:53 UTC, etwest commented on tools/benchmark/graphcc_bench.cpp
> +        GraphStreamUpdate &upd = upds[i];
yes intentional

2023-11-09 21:01 UTC, etwest commented on src/sketch.cpp
> +  buckets = new Bucket[num_buckets];
Nah

2023-12-14 17:03 UTC, DanielDeLayo approved these changes

2023-12-18 03:13 UTC, merged