refactor: use external node type
GraphStreamingProject/GraphZeppelin pull request #60
Opened 2021-10-12 19:27 UTC by Victor-C-Zhang

2021-10-19 00:15 UTC, etwest commented on CMakeLists.txt
> +  GIT_TAG         "commonComp"
Change this before merging

2021-10-19 00:16 UTC, etwest approved these changes
Approve pending change to branch

2021-10-19 00:21 UTC, etwest requested changes
Actually, I'm a bit concerned about this. Currently we have two types in the codebase. There's a 64 bit value which we use for the bucket_a values which we call Node (or something) and there's a 32 bit value which we use for node_id_t and bucket_c. I think these changes would need to somehow incorporate both of these types.

2021-10-22 02:06 UTC, Victor-C-Zhang commented
> Actually, I'm a bit concerned about this. Currently we have two types in the codebase. There's a 64 bit value which we use for the bucket_a values which we call Node (or something) and there's a 32 bit value which we use for node_id_t and bucket_c. I think these changes would need to somehow incorporate both of these types.

I don’t think `node_id_t` is used in the streaming repo. iirc it’s used to number buffers in the buffer tree only (?)

2021-10-22 13:39 UTC, etwest commented
> > Actually, I'm a bit concerned about this. Currently we have two types in the codebase. There's a 64 bit value which we use for the bucket_a values which we call Node (or something) and there's a 32 bit value which we use for node_id_t and bucket_c. I think these changes would need to somehow incorporate both of these types.
> 
> I don’t think `node_id_t` is used in the streaming repo. iirc it’s used to number buffers in the buffer tree only (?)

It's also used by the standalone buffering and we might want to think about expanding its use. 64bit bucket_a only works if we have 32 bit node ids

2021-11-09 22:48 UTC, closed without merging