Split up Graph::boruvka_emulation into smaller pieces
GraphStreamingProject/GraphZeppelin pull request #86
Opened 2022-02-21 04:04 UTC by edeturk32

I moved the code in Graph::boruvka_emulation for sampling supernodes, identifying outgoing edges, and merging supernodes to their own functions.
To make this easier, I promoted the local "modified" variable in the do/while loop to a member variable of the Graph class. This way, Graph::supernodes_to_merge can return just one value.

2022-02-21 15:41 UTC, etwest commented
Do you have numbers on how these changes effect query performance?

2022-02-21 15:44 UTC, etwest commented on include/graph.h
> +  void merge_supernodes(
Style nit: To make your function declarations consistent with the rest of the code, please have arguments on one line and make a newline if necessary for length. See generate_delta_node for an example of how we do this.

2022-02-21 15:51 UTC, etwest commented on src/graph.cpp
> +    std::vector<std::vector<node_id_t>> to_merge = supernodes_to_merge(
Style nit: Arguments on the same line

2022-02-21 21:32 UTC, etwest commented
> Do you have numbers on how these changes effect query performance?

Do you have access to our lab machine? If not I can run this experiment to get these numbers.

2022-02-22 03:23 UTC, edeturk32 commented
> Do you have access to our lab machine? If not I can run this experiment to get these numbers.
I don't think I have access to the lab machine

2022-02-22 17:25 UTC, etwest commented
> I don't think I have access to the lab machine

Okay I will run the experiment later today. I'll post the results here after that and we can go from there.

2022-02-23 21:43 UTC, etwest commented
| Backup In Mem | Branch: main, cc alg latency | Branch: cc_split, cc alg latency |
|-|-|-|
| ON | 1.25, 1.28, 0.40, 0.32, 0.32, 0.32, 0.32, 0.32, 0.32, 0.32 | 1.40 1.24 0.51 0.33 0.33 0.33 0.33 0.34 0.33 0.33 |
| OFF | 23.6, 23.6, 24.0, 24.0, 25.0, 25.6, 25.6, 25.5, 25.6, 25.7 | 26.5, 26.0, 26.0, 25.9, 26.0, 26.1, 26.0, 25.6, 25.8, 25.8  |

Looks like your changes make the cc algorithm a little bit slower.

2022-02-23 21:45 UTC, etwest requested changes
* Change style to address style nits
* Make functions inline to try to address performance impact

2022-02-24 04:40 UTC, Victor-C-Zhang commented on src/graph.cpp
> +inline void Graph::sample_supernodes(std::pair<Edge, SampleSketchRet> *query,
does this actually improve performance?

2022-02-26 19:34 UTC, etwest commented on src/graph.cpp
> +inline void Graph::sample_supernodes(std::pair<Edge, SampleSketchRet> *query,
Seems like it doesn't really. I will push a change in a moment that does improve performance.

2022-02-26 19:41 UTC, etwest commented
| Backup In Mem | Branch: cc_split, cc alg latency |
|-|-|-|
| ON | 1.38 1.37 0.38 0.32 0.32 0.32 0.32 0.32 0.32 0.32 |

Performance of commit: a4819a7

2022-02-26 19:46 UTC, etwest approved these changes
I think this is good enough. Thanks Ethan!

2022-02-27 20:25 UTC, merged